# latexmkrc para docs/*/main.tex
add_cus_dep('glo', 'gls', 0, 'makeglossaries');

sub makeglossaries {
  my ($base_name) = @_;
  system("makeglossaries $base_name");
}

$bibtex   = 'biber';
$pdflatex = 'pdflatex -interaction=nonstopmode -halt-on-error';
$pdf_mode = 1;
