name: Build LaTeX docs
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LaTeX
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
      - name: Install latexmk
        run: |
          sudo apt-get update
          sudo apt-get install -y latexmk
      - name: Compile LaTeX to PDF
        run: |
          mkdir -p build
          for file in tomos/*.tex; do
            latexmk -pdf -interaction=nonstopmode -output-directory=build "$file"
          done
      - name: Upload PDFs to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.pdf
