name: build-latex
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >
            latexmk scheme-small biblatex biber
            amsmath siunitx glossaries cleveref
            geometry hyperref xcolor graphicx
      - name: Build tomos
        run: |
          cd docs
          for t in $(ls -d tomo*/); do
            latexmk -pdf -interaction=nonstopmode -halt-on-error $t/main.tex
          done
