name: Build LaTeX docs
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          packages: |
            latexmk
            texlive-latex-extra
            texlive-fonts-recommended
            texlive-fonts-extra
            texlive-latex-recommended
            texlive-bibtex-extra
      - name: Compile LaTeX to PDF
        run: |
          mkdir build
          for file in tomos/*.tex; do
            latexmk -pdf -interaction=nonstopmode -output-directory=build "$file"
          done
      - name: Upload PDFs to Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*.pdf
